services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-api
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      DB_HOST: localhost
      DB_USER: alfa
      DB_PASSWORD: alfa
      DB_NAME: testapi
      DB_PORT: 5432
    networks:
      - go-network

networks:
  go-network:
    driver: bridge
